const ThemeManager = require('../utils/ThemeManger');

cc.Class({
    extends: cc.Component,

    properties: {
        bgSprite: cc.Sprite,

        coverSprite: cc.Sprite,
    },

    // LIFE-CYCLE CALLBACKS:

    // onLoad () {},

    start () {

    },

    updateItem() {
        ThemeManager.setTopBgBuildSpriteFrame(1, this.bgSprite);
        ThemeManager.setTopCoverSpriteFrame(1, this.coverSprite);
    },

    deleteItem() {
        this._listViewAdapter.removeItem(this);
    },

    // update (dt) {},
});
